--about README.md
--ignore SGM-Perch-BirdNET/INSTALL_COPY_TO_REAPER_SCRIPTS.txt
--ignore SGM-Perch-BirdNET/sfx_ebird_local_list_updater.py
--ignore SGM-Perch-BirdNET/sfx_perch_auto_name_helper.py
--commit-template "index: $changelog

[ci skip]"
