// Generated from the exact reusable stacks in:
// ai mastering training.RPP
// Regenerate with scripts/generate-training-cue-bank.mjs.

export const TRAINING_SFX_CUES = [
  "whip crack",
  "BREAKING, SCREAM",
  "DIGITAL COUNTDOWN",
  "ELECTRONIC PING OF A NOTIFICATION",
  "CHAIR MOVEMENT",
  "FOOTSTEPS APPROACHING",
  "impact",
  "NOTIFICATION SOUND",
  "PING ELETTRONICO, LEGGERO RONZIO",
  "QUICK FOOTSTEPS",
  "VIOLENT IMPACT",
  "battle",
  "BLOOD DRIPPING",
  "BUS INTERIOR",
  "CHOKING SOUNDS",
  "COMPUTERIZED NOTIFICATION SOUND",
  "CORK POPPING",
  "COUNTDOWN",
  "crowd murmur",
  "CRUNCH, SCREAM",
  "DEEP BREATH",
  "DIGITAL TRANSFORMATION",
  "DIGITAL WHOOSH",
  "door open, footstep echo",
  "DOOR SLAMMING",
  "DOORS OPEN",
  "EARTH FORMING INTO BLADE",
  "EARTHQUAKE RUMBLE",
  "ENERGY BLAST",
  "FIRE WHOOSH",
  "FLESH WOUND",
  "FOOTSTEPS",
  "FOREST SOUNDS",
  "FRIGHTENED CRY",
  "HORROR MOVIE AMBIENCE",
  "IMPACT ON STONE",
  "LIGHTS FLICKERING",
  "MAGICAL DISCOVERY",
  "MUFFLED SCREAM",
  "NOTIFICATION PING",
  "PUNCH IN THE STOMACH",
  "quick footstep",
  "QUICK MOVEMENT",
  "QUIET NIGHT AIR",
  "SCHOOL BELL",
  "SHOTGUN BLAST",
  "STERILE LABORATORY",
  "STRUGGLE",
  "SUDDEN MOVEMENT",
  "TABLET CALL INITIATION",
  "TELEPORTATION",
  "VICTORY FANFARE",
  "ABRUPT COLLECTIVE INSPIRATION",
  "ACADEMY ARMORY",
  "ACADEMY GROUNDS",
  "ALARM CLOCK RINGS",
  "ALARMED SHOUT",
  "alarmed shout, human scream",
  "ANGRY SHOUT",
  "angry shout, human yell",
  "ARENA ATMOSPHERE",
  "arrow whistle",
  "ARROW WHISTLING",
  "ARROWS WHISTLING THROUGH AIR",
  "attack",
  "attack shout, battle cry",
  "ATTACKS AND SHOUTS",
  "BACKGROUND MUSIC IN A SHOP, DOOR BELL",
  "BACKGROUND VOICES, TELEPORTATION NOISE",
  "BACKPACK UNZIPPING",
  "ball whistle air, thud",
  "barrier crumble",
  "BARRIER CRUMBLING",
  "bird",
  "BIRDS CHIRPING",
  "BLOOD POURING INTO VIAL",
  "blow impact",
  "body fall",
  "BODY FALLING",
  "body move, floor scrape",
  "body slam, wall impact",
  "BODY SLAMMED AGAINST WALL",
  "BODY SLAMMING AGAINST WALL",
  "body stumble, trip sound",
  "BODY STUMBLING",
  "BODY WRITHING ON FLOOR",
  "bone break",
  "BONE CRACK",
  "BONES BREAKING",
  "BOOK CRACKING AND DISSOLVING",
  "BOOK PAGES TURNING",
  "BOOK VIBRATING",
  "BOWSTRING TENSION",
  "BRUTAL IMPACT",
  "BUMPY BUS RIDE",
  "BUS ENGINE",
  "BUS ENGINE STARTING",
  "buzz",
  "buzz sound, vibration sound",
  "buzz, snap",
  "BUZZING AND LIGHT VIBRATION",
  "capsule close",
  "CAPSULE CLOSING",
  "chain drag, door creak",
  "chair creak, chair move",
  "chair move",
  "choking",
  "city noise, people talk, traffic",
  "CITY NOISES, PEOPLE TALKING, TRAFFIC",
  "CLASSROOM",
  "claw scratch, step creak",
  "CLAWS SCRATCHING ON STEPS",
  "clock tick, metal scrape",
  "cloth tear",
  "CLOTH TEARING",
  "CLOTHES RUSTLING AND SUITCASE OPENING",
  "COMBAT SCREAMS, MOANS OF PAIN",
  "COMPUTER BEEP",
  "COMPUTER INTERFACE BEEP",
  "computer start",
  "COMPUTER STARTUP SOUND",
  "COUGHING BLOOD",
  "CREAKING CHAIR AS VITO LEANS BACK",
  "CREATURE GROWL",
  "crowd dispers, footstep",
  "crowd movement",
  "CROWD MURMURING",
  "CROWD PARTING",
  "CRYSTALLINE TINKLING",
  "data scroll",
  "DATA SCROLLING",
  "debris fall",
  "DEEP GONG",
  "delicate electronic",
  "DELICATE ELECTRONIC SOUNDS",
  "digital beep",
  "DIGITAL INTERFACE BEEPS",
  "DIGITAL NOTIFICATION BEEPS",
  "DISTANT COMBAT SOUNDS",
  "DISTANT CREATURE SOUNDS",
  "distant creature, monster roar",
  "DOOR BURSTING OPEN",
  "door knock, door open",
  "DOOR KNOCK, OPENS",
  "DOOR OPEN",
  "door open bang",
  "DOOR OPENING",
  "DOOR OPENING AGAIN, MORE ECHOING FOOTSTEPS",
  "DOOR OPENING, ECHOING FOOTSTEPS",
  "DORMITORY INTERIOR",
  "DRAGGING SOUNDS",
  "dragging surface",
  "DRY LEAVES RUSTLING AND METAL CREAKING",
  "dry rustle, metal creak",
  "EARTH MANIPULATION SOUNDS",
  "EARTH RESHAPING",
  "earth rumble",
  "ECHOING FOOTSTEPS",
  "ELECTRONIC HUM OF CAPSULES, MUFFLED VOICES",
  "ELECTRONIC NOTIFICATION, SLIGHT BUZZING FROM THE SYSTEM",
  "ELECTRONIC PING",
  "ELECTRONIC PING, POP-UP SOUND",
  "FABRIC RUSTLING",
  "FAINT MURMURING THAT GRADUALLY FADES",
  "FAST TYPING ON KEYBOARD",
  "fight blade clash",
  "fireball whoosh",
  "flames hiss, electric discharge",
  "FLAMES HISSING, ELECTRIC DISCHARGE",
  "flesh squish",
  "FLESH TEARING",
  "FLYING VEHICLES",
  "footstep echo, hallway footstep",
  "FOOTSTEPS AND RODENT SQUEAKS",
  "footsteps approach surface",
  "FOOTSTEPS ECHOING IN EMPTY HALLWAY",
  "FOOTSTEPS ECHOING IN THE ARENA",
  "footsteps hurried",
  "FOOTSTEPS ON LEAVES",
  "FOOTSTEPS ON RING FLOOR",
  "footsteps quick",
  "footsteps sneak",
  "FOOTSTEPS STOPPING",
  "FOREST AMBIENCE",
  "FOREST EVENING",
  "FRANTIC SEARCHING",
  "FRIENDLY PAT ON SHOULDER",
  "FRIENDS LAUGHING",
  "FUTURISTIC MACHINERY",
  "GLASS VIAL TAPPING",
  "GLASSES HANDLING",
  "glow",
  "ground crumble",
  "GROUND CRUMBLING",
  "GULP SOUND",
  "GULPING WATER",
  "heart beat",
  "HEARTBEAT",
  "HEARTBEAT ACCELERATING",
  "heartbeat fast",
  "HEAVY BREATHING",
  "HEAVY FOOTSTEPS APPROACHING",
  "HEAVY ROCK IMPACT",
  "hologram activate",
  "HOLOGRAPHIC DISPLAY ACTIVATING",
  "HOLOGRAPHIC SPINES ATTACKING",
  "horror scream",
  "HOT DESERT ARENA",
  "HOT SUMMER DAY",
  "human breath",
  "human scream, pain",
  "hurried footstep, human breath",
  "HURRIED FOOTSTEPS, HEAVY BREATHING",
  "ice crack, footsteps",
  "ICE CRACKING, MURMURS OF AMAZEMENT AMONG THE OTHER RECRUITS",
  "ICE FORMING",
  "IMPACT OF ROCK HITTING BODY",
  "impact punch",
  "impact, ice crunch",
  "INTENSE HEAT",
  "interface activate",
  "INTERFACE ACTIVATION",
  "INTERFACE BEEP",
  "interior murmur fade",
  "KEYBOARD NOISE",
  "keyboard typ, typ sound",
  "KICK",
  "kick impact",
  "leaves rustle",
  "level chime",
  "LEVEL UP CHIME",
  "LIBRARY",
  "LIBRARY AMBIENCE",
  "LIBRARY WHISPERS",
  "LIGHT ELECTRONIC BUZZ",
  "LIGHT SNORING",
  "LIGHT SPHERE HUMMING",
  "LIQUID GULPING",
  "LIQUID POURING",
  "LONG SIGH",
  "LOUD COMMANDING VOICE",
  "LOUD KNOCKING ON DOOR",
  "LOUD LAUGHTER, SOME STUDENTS TURN AROUND IN SURPRISE",
  "LOW HUM OF MACHINERY",
  "MAGICAL APPEARANCE",
  "MAGICAL ENERGY FORMING",
  "MAGICAL EQUIPMENT ACTIVATION",
  "MAGICAL GLOW",
  "MAGICAL GLOWING",
  "MAGICAL GLOWING SOUND",
  "MAGICAL HEALING",
  "MAGICAL NOTIFICATION",
  "MAGICAL TRANSFORMATION",
  "MECHANICAL BEATING",
  "metal balls fall ground",
  "METAL BALLS FALLING TO THE GROUND",
  "METAL CLINK",
  "METAL TARGETS EMERGING",
  "MILITARY METROPOLIS",
  "MILITARY SHOUTING",
  "MILITARY TRAINING GROUND",
  "MOCKING LAUGHTER",
  "MOMENT OF REALIZATION",
  "morphing",
  "MUFFLED FOOTSTEPS",
  "MUFFLED SOUNDS",
  "MURMUR OF THE CROWD",
  "NEEDLE PRICK",
  "NIGHT ROOFTOP",
  "notification pop",
  "OMINOUS HUMMING",
  "OUTDOOR ARENA",
  "OUTDOOR FIELD",
  "OUTDOOR MILITARY BASE",
  "OUTDOOR STREET",
  "PAINED BREATHING SUBSIDING",
  "PAINFUL SCREAM",
  "phone ring",
  "PHYSICAL STRUGGLE",
  "physical struggle, scuffle sound",
  "PING",
  "PING DI UNA NOTIFICA",
  "PING NOTIFICATION",
  "pop notification",
  "POP-UP NOTIFICATION",
  "PORTAL ABSORPTION",
  "portal absorption, whoosh sound",
  "PRIVACY SPHERE ACTIVATION",
  "PUNCH IMPACT",
  "punch impact flesh",
  "PUNCHES AND MUFFLED GROANS",
  "QUIET APARTMENT",
  "rapid footstep",
  "RAPID FOOTSTEPS",
  "rapid scratch",
  "RAPID SCRATCHING SOUND",
  "realization moment",
  "receiver hiss",
  "REFRIGERATOR DOOR OPENING",
  "rock clash, body impact",
  "rock fly",
  "rock impact",
  "rock impact body",
  "rock sprout, impact",
  "rocks bounce exterior, wind howl exterior",
  "ROCKS BOUNCING, WIND HOWLING",
  "ROCKS CLASHING, BODY HITTING GROUND",
  "ROCKS FLYING THROUGH AIR",
  "ROCKS SPROUTING, IMPACTS",
  "rush footstep",
  "RUSHING FOOTSTEPS",
  "RUSTLE OF PAGES",
  "RUSTLING",
  "RUSTLING LEAVES",
  "SCHOOL BELL RINGS",
  "SCHOOL CORRIDOR",
  "SCHOOL HALLWAY",
  "scream moan",
  "SERGEANT SHOUTING",
  "SHALLOW BREATHING",
  "SHARP BLOWS AND THE SOUND OF A FALL",
  "SHARP WHISTLE",
  "shop music, door bell",
  "SHRILL ALARM",
  "silence",
  "SKIN TINGLING",
  "SLASHING ATTACKS",
  "Soft clicks and beeps from instruments",
  "SOUND OF A BODY HITTING THE WALL",
  "SOUND OF AN OBJECT BEING THROWN INTO THE AIR",
  "SOUNDS OF COMBAT, BLOWS ON THE CARPETS",
  "sphere charge",
  "SPHERE CHARGING",
  "sphere whoosh",
  "SQUISHY FLESH SOUND",
  "STRETCHING SOUND",
  "STUDENTS MURMURING",
  "STUDENTS MURMURING AND FOOTSTEPS",
  "SUBTLE THREAT",
  "SUDDEN APPEARANCE",
  "sudden move",
  "SUDDEN NOISE",
  "SUDDEN REALIZATION",
  "SUSPICIOUS WHISPERS",
  "SWIFT ATTACK MOVEMENT",
  "swirl wind",
  "SWORD SLASH",
  "sword unsheathe metal",
  "SYSTEM ALERT BEEP",
  "TABLET NOTIFICATION BEEP",
  "teleport",
  "TELEPORTATION NOISE, CONFUSION OF VOICES",
  "teleportation sound",
  "TENSE HEARTBEAT",
  "TENSE SILENCE",
  "TEST STARTING SIGNAL",
  "TESTING AREA",
  "TESTING AREA CROWD MURMURS",
  "THE DOOR CLOSES SLOWLY",
  "THOUGHTFUL MUMBLING",
  "thud",
  "TRAINING AREA",
  "TREE THUD",
  "TV NEWS JINGLE",
  "VIOLENT IMPACTS",
  "VIOLENT PUNCHES",
  "VOICE APPROACHING",
  "WAR SOUNDS DISTANT",
  "WATER BLADES FLYING",
  "water cut air",
  "water drip",
  "water impact",
  "WATER SPLASH",
  "water splash, wipe",
  "water spray, ice crack",
  "WEAK IMPACT",
  "WEAPON UNSHEATHING",
  "whip crack violent",
  "whip slice object",
  "WHISPERING, PAGE TURNING",
  "WHISTLING WIND, IMPACT OF ROCKS",
  "WHOOSHING BLACK SPHERE",
  "WIND BLADES CUTTING AIR",
  "wind cut air",
  "wind whistle exterior, rocks impact",
  "WIND WHISTLING THROUGH RUINED BUILDINGS",
  "wipe, cry",
  "WOOD SPLITTING"
] as const;

export const TRAINING_AMBIENT_CUES = [
  "DARK ALLEY",
  "CITY STREETS",
  "abandoned station interior",
  "city street",
  "crowd commotion",
  "FOOTSTEPS ECHOING",
  "GENERAL'S OFFICE",
  "interior murmur",
  "INTERROGATION ROOM",
  "LARGE METALLIC ROOM",
  "NIGHT STREET",
  "RUINED CITY",
  "ruins",
  "silence",
  "TENSE INTERROGATION",
  "TOY STORE",
  "VIRTUAL ARENA",
  "ABANDONED BUILDING",
  "academy grounds",
  "ACADEMY HALLWAY",
  "alien landscape",
  "BACK ALLEY QUIET DRIPS",
  "BUSY CITY STREET",
  "BUSY CITY STREET DAY",
  "CITY NIGHT DISTANT TRAFFIC",
  "CITY RAIN WET TRAFFIC",
  "COMPUTER INTERFACE STARTUP",
  "corridor",
  "creature ruins",
  "desert wind",
  "DESOLATE ALIEN LANDSCAPE",
  "desolate city",
  "DESOLATE CITYSCAPE",
  "desolate landscape",
  "DIFFERENT LOCATION ON ALIEN PLANET",
  "DORMITORY ROOM",
  "dormitory room ambience",
  "DOWNTOWN NIGHTLIFE STREET",
  "empty hallway",
  "EMPTY HALLWAY ECHOES",
  "FORMAL MEETING ROOM",
  "FUTURISTIC TECHNOLOGY HUM",
  "hallway",
  "HOSPITAL",
  "hospital ambience",
  "INFIRMARY ROOM",
  "interrogation room ambience",
  "isolation",
  "MANA STORM ENERGY ATMOSPHERE",
  "medical room ambience",
  "metal room",
  "MUFFLED ISOLATION",
  "night",
  "NIGHT ATMOSPHERE",
  "office",
  "OFFICE INTERIOR",
  "PORTAL ENERGY",
  "PORTAL HUM",
  "QUIET ROOM WITH TV IN BACKGROUND",
  "QUIET SUBURBAN STREET",
  "rain",
  "reality",
  "ROOFTOP CITY WIND",
  "RUINED BUILDING",
  "RUINS WITH CREATURE MOVEMENTS",
  "SCHOOL CORRIDOR",
  "SCHOOL COURTYARD",
  "SMALL DORMITORY ROOM",
  "STREET MARKET BAZAAR CROWD",
  "technology hum",
  "TENSE CONFRONTATION",
  "tense room",
  "TRAFFIC JAM HORNS",
  "underground platform",
  "virtual reality",
  "VIRTUAL REALITY TRAINING ROOM",
  "virtual room",
  "WEEKEND ACADEMY GROUNDS"
] as const;

export const TRAINING_CUE_BANK_META = {
  source: "ai mastering training.RPP",
  reusableStacks: 557,
  sfxStacks: 458,
  ambientStacks: 99,
  distinctSfx: 388,
  distinctAmbient: 78,
  musicStacks: 0,
} as const;
